"""add friendship model

Revision ID: 253ea971bd74
Revises: 58b5da47d18c
Create Date: 2022-07-02 14:12:48.264194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253ea971bd74'
down_revision = '58b5da47d18c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.UniqueConstraint('user_id', 'friend_id', name='unique_friendships')
    )
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friendships_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friendships_user_id'))

    op.drop_table('friendships')
    # ### end Alembic commands ###
